from .account import AccountView
from .addrecord import AddRecordView
from .connect import ConnectView
from .createstream import CreateStreamView
from .displayname import DisplayNameView
from .hosts import HostsView
from .index import index_view
from .linkspotify import LinkSpotifyView
from .queue import QueueView
from .recordslist import RecordsListView
from .signin import SignInView
from .signup import SignUpView
from .stream import StreamView
