# Generated by Django 2.1.1 on 2019-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='showing_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
