# Generated by Django 3.0 on 2020-02-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_active_stream_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
