# Generated by Django 2.1.1 on 2019-08-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_showing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='showing_uuid',
        ),
        migrations.AddField(
            model_name='profile',
            name='active_showing_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
