# Generated by Django 3.0 on 2019-12-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=234, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotify_scope',
            field=models.CharField(blank=True, max_length=208, null=True),
        ),
    ]
