# Generated by Django 3.0 on 2020-01-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191203_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotify_scope',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
