# Generated by Django 3.0 on 2020-03-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_last_active_stream_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
