# Generated by Django 3.0 on 2020-03-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_activated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activated_stream_redirect',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
