# Generated by Django 3.0 on 2020-03-21 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_activated_stream_redirect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_active_stream_uuid',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 21, 5, 33, 0, 682610)),
            preserve_default=False,
        ),
    ]
