# Generated by Django 2.1.1 on 2019-07-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190728_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='showing_uuid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
