# Generated by Django 2.1.1 on 2019-03-18 04:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('code', models.CharField(editable=False, max_length=4)),
                ('board', models.CharField(max_length=92)),
                ('black', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blacks', to=settings.AUTH_USER_MODEL)),
                ('white', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
