# Generated by Django 2.1.1 on 2019-04-26 02:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('join_code', models.CharField(editable=False, max_length=4)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_private', models.BooleanField()),
                ('game_clock', models.FloatField(default=3000)),
                ('move_rebound', models.FloatField(default=5)),
                ('black_time', models.FloatField(default=3000)),
                ('black_status', models.CharField(choices=[('pending_game_start', 'pending_game_start'), ('pending_opponent', 'pending_opponent'), ('warning_game_cancellation', 'warning_game_cancellation'), ('complete', 'complete'), ('my_turn', 'my_turn'), ('their_turn', 'their_turn')], max_length=32)),
                ('white_time', models.FloatField(default=3000)),
                ('white_status', models.CharField(choices=[('pending_game_start', 'pending_game_start'), ('pending_opponent', 'pending_opponent'), ('warning_game_cancellation', 'warning_game_cancellation'), ('complete', 'complete'), ('my_turn', 'my_turn'), ('their_turn', 'their_turn')], max_length=32)),
                ('steps', models.IntegerField(default=0)),
                ('board', models.CharField(max_length=92)),
                ('black_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blacks', to=settings.AUTH_USER_MODEL)),
                ('white_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChessSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('action', models.CharField(choices=[('create_match', 'create_match'), ('join_match', 'join_match'), ('close_match', 'close_match'), ('resign_match', 'resign_match'), ('take_move', 'take_move'), ('suggest_move', 'suggest_move'), ('create_undo_request', 'create_undo_request'), ('approve_undo_request', 'approve_undo_request'), ('reject_undo_request', 'reject_undo_request'), ('undo_move', 'undo_move')], max_length=32)),
                ('board', models.CharField(max_length=92)),
                ('step', models.IntegerField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='actors', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='snapshots', to='chess.ChessGame')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
