# Generated by Django 2.1.1 on 2019-03-10 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=92)),
                ('black', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blacks', to=settings.AUTH_USER_MODEL)),
                ('white', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
