# Generated by Django 2.1.1 on 2019-04-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgame',
            name='black_user',
        ),
        migrations.RemoveField(
            model_name='chessgame',
            name='white_user',
        ),
        migrations.RemoveField(
            model_name='chesssnapshot',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='chesssnapshot',
            name='game',
        ),
        migrations.DeleteModel(
            name='ChessGame',
        ),
        migrations.DeleteModel(
            name='ChessSnapshot',
        ),
    ]
