# Generated by Django 2.1.1 on 2019-03-10 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chess',
            name='id',
        ),
        migrations.AddField(
            model_name='chess',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
