# Generated by Django 2.1.1 on 2019-08-03 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_join', models.DateTimeField(auto_now_add=True)),
                ('timestamp_last_active', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(editable=False, max_length=32)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='music.Showing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
