# Generated by Django 2.2.5 on 2019-11-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='played_at',
            field=models.DateTimeField(null=True),
        ),
    ]
