# Generated by Django 3.0.3 on 2020-04-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="current_tracklisting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="now_playing_tracklisting",
                to="music.TrackListing",
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="tracklisting_begun_at",
            field=models.DateTimeField(null=True),
        ),
    ]
