# Generated by Django 2.2.5 on 2019-12-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='display_name',
            new_name='holder_name',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='display_uuid',
            new_name='holder_uuid',
        ),
    ]
