# Generated by Django 2.1.1 on 2019-07-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='primary_color',
            new_name='color_0',
        ),
        migrations.AddField(
            model_name='album',
            name='color_1',
            field=models.CharField(default='#000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='color_2',
            field=models.CharField(default='#000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='color_3',
            field=models.CharField(default='#000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='color_4',
            field=models.CharField(default='#000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='art',
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
