# Generated by Django 2.1.1 on 2019-07-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='showing',
            old_name='actual_showtime',
            new_name='showtime_actual',
        ),
        migrations.RenameField(
            model_name='showing',
            old_name='scheduled_showtime',
            new_name='showtime_scheduled',
        ),
        migrations.AlterField(
            model_name='showing',
            name='status',
            field=models.CharField(default='scheduled', max_length=128),
        ),
    ]
