# Generated by Django 2.1.1 on 2019-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
