# Generated by Django 2.2.5 on 2019-11-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_record_played_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='number',
        ),
    ]
