# Generated by Django 3.0 on 2019-12-08 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20191208_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='current_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='now_playing_at_showings', to='music.Record'),
        ),
    ]
