# Generated by Django 3.0.3 on 2020-04-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_auto_20200405_2244"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="paused_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="stream",
            name="tracklisting_terminates_at",
            field=models.DateTimeField(null=True),
        ),
    ]
