# Generated by Django 2.1.1 on 2019-07-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190727_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='color_0',
        ),
        migrations.RemoveField(
            model_name='album',
            name='color_1',
        ),
        migrations.RemoveField(
            model_name='album',
            name='color_2',
        ),
        migrations.RemoveField(
            model_name='album',
            name='color_3',
        ),
        migrations.RemoveField(
            model_name='album',
            name='color_4',
        ),
        migrations.AlterField(
            model_name='showing',
            name='showtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='showing',
            name='status',
            field=models.CharField(default='scheduled', editable=False, max_length=128),
        ),
    ]
