# Generated by Django 2.1.1 on 2019-08-01 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190731_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='id',
        ),
        migrations.AddField(
            model_name='showing',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
