# Generated by Django 3.0 on 2019-12-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20191208_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
