# Generated by Django 3.0 on 2020-02-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_stream_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='tags',
            field=models.CharField(default='Jazz, Hip-Hop', max_length=128),
            preserve_default=False,
        ),
    ]
