# Generated by Django 3.0.3 on 2020-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_auto_20200409_0620"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="spotify_duration_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
