# Generated by Django 3.0 on 2019-12-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_ticket_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='track_timestamp',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
