# Generated by Django 2.1.1 on 2019-07-28 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190728_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracks', to='music.Album'),
        ),
    ]
