# Generated by Django 3.0.3 on 2020-04-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200409_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='record_begun_at',
            field=models.DateTimeField(null=True),
        ),
    ]
