# Generated by Django 3.0.3 on 2020-04-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_stream_record_begun_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracklisting",
            name="relative_duration",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
