# Generated by Django 3.0 on 2020-02-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
