# Generated by Django 2.1.1 on 2019-07-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190728_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default='ok', max_length=128),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='track',
            name='track_name',
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('number', 'album')},
        ),
    ]
