# Generated by Django 3.0.3 on 2020-04-30 06:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_tracklisting_relative_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='tracklisting_begun_at',
            new_name='played_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='current_record',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='last_status_change_at',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='tracklisting_terminates_at',
        ),
        migrations.RemoveField(
            model_name='tracklisting',
            name='relative_duration',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 6, 26, 0, 386581)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='storage_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='storage_filename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='storage_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='storage_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='youtube_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='youtube_img_high',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='youtube_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='current_queue',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_stream', to='music.Queue'),
        ),
        migrations.AddField(
            model_name='stream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tracklisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('joined', 'Joined'), ('left', 'Left'), ('comment', 'Commented'), ('spinning', 'Spinning'), ('play', 'Played'), ('paused', 'Paused'), ('next', 'Next'), ('skip', 'Skipped')], max_length=12),
        ),
        migrations.AlterField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='spotify_img',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='spotify_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('created_stream', 'Created stream'), ('added_as_host', 'Added as host')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 4, 30, 6, 26, 11, 42585)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QueueListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_at_ms', models.PositiveIntegerField()),
                ('end_at_ms', models.PositiveIntegerField()),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='queue_listings', to='music.Queue')),
                ('track_listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='queued_listing', to='music.TrackListing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
