# Generated by Django 2.1.1 on 2019-07-28 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20190728_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='music.Track'),
        ),
    ]
