# Generated by Django 3.0 on 2020-03-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='spotify_uri',
            field=models.CharField(default='hello', max_length=128),
            preserve_default=False,
        ),
    ]
