# Generated by Django 3.0 on 2020-03-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_record_spotify_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='spotify_img',
            field=models.CharField(default='foo', max_length=256),
            preserve_default=False,
        ),
    ]
