# Generated by Django 3.0.3 on 2020-05-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0009_queue_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_hidden_when_idle",
            field=models.BooleanField(default=False),
        ),
    ]
