# Generated by Django 3.0 on 2020-03-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_record_spotify_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='spotify_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_uri',
            field=models.CharField(max_length=64),
        ),
    ]
