# Generated by Django 3.0 on 2020-03-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20200308_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='owner_name',
            field=models.CharField(default='foobarbaz', max_length=128),
            preserve_default=False,
        ),
    ]
