# Generated by Django 3.0.3 on 2020-05-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0011_auto_20200522_0534"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="initialization_segment",
            field=models.BinaryField(blank=True, max_length=161, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_speaking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="partial_block",
            field=models.BinaryField(blank=True, max_length=1024, null=True),
        ),
    ]
