# Generated by Django 3.0 on 2020-03-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_stream_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
