# Generated by Django 3.0.3 on 2020-05-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20200526_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sent_initialization_segment',
            field=models.BooleanField(default=False),
        ),
    ]
