# Generated by Django 3.0.3 on 2020-05-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_ticket_sent_initialization_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='initialization_segment',
            field=models.BinaryField(blank=True, max_length=500, null=True),
        ),
    ]
