# Generated by Django 3.0 on 2020-03-21 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0016_auto_20200321_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.CharField(default=1, editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
