# Generated by Django 3.0 on 2020-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_remove_ticket_holder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='vote_controlled',
        ),
        migrations.AddField(
            model_name='stream',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
